name: build-latex-ja-image

on:
  push:
    branches:
      - 'main'
    paths:
     - 'latex-ja/**'
     - '.github/workflows/build-latex-ja-image.yaml'
  schedule:
    - cron: "0 0 1 * *"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Docker meta (debian-11)
        id: meta-debian-11
        uses: docker/metadata-action@v4
        with:
          images: milran/latex-dev-container-ja
          bake-target: docker-meta-debian-11
          tags: |
            type=schedule,pattern={{date 'YYYYMMDD'}},prefix=0-debian-11-
            type=sha,prefix=0-debian-11-
            type=raw,value=0-debian-11,enable={{is_default_branch}}
      -
        name: Docker meta (debian-10)
        id: meta-debian-10
        uses: docker/metadata-action@v4
        with:
          images: milran/latex-dev-container-ja
          bake-target: docker-meta-debian-10
          tags: |
            type=schedule,pattern={{date 'YYYYMMDD'}},prefix=0-debian-10-
            type=sha,prefix=0-debian-10-
            type=raw,value=0-debian-10,enable={{is_default_branch}}
      -
        name: Docker meta (ubuntu-22.04)
        id: meta-ubuntu-22-04
        uses: docker/metadata-action@v4
        with:
          images: milran/latex-dev-container-ja
          bake-target: docker-meta-ubuntu-22-04
          tags: |
            type=schedule,pattern={{date 'YYYYMMDD'}},prefix=0-ubuntu-22.04-
            type=sha,prefix=0-ubuntu-22.04-
            type=raw,value=0-ubuntu-22.04,enable={{is_default_branch}}
      -
        name: Docker meta (ubuntu-20.04)
        id: meta-ubuntu-20-04
        uses: docker/metadata-action@v4
        with:
          images: milran/latex-dev-container-ja
          bake-target: docker-meta-ubuntu-20-04
          tags: |
            type=schedule,pattern={{date 'YYYYMMDD'}},prefix=0-ubuntu-20.04-
            type=sha,prefix=0-ubuntu-20.04-
            type=raw,value=0-ubuntu-20.04,enable={{is_default_branch}}
      -
        name: Docker meta (ubuntu-18.04)
        id: meta-ubuntu-18-04
        uses: docker/metadata-action@v4
        with:
          images: milran/latex-dev-container-ja
          bake-target: docker-meta-ubuntu-18-04
          tags: |
            type=schedule,pattern={{date 'YYYYMMDD'}},prefix=0-ubuntu-18.04-
            type=sha,prefix=0-ubuntu-18.04-
            type=raw,value=0-ubuntu-18.04,enable={{is_default_branch}}
      - name: Merge buildx bake files
        run: |
          jq -s 'reduce .[] as $j ({}; . * $j)' \
            ${{ steps.meta-debian-11.outputs.bake-file }} \
            ${{ steps.meta-debian-10.outputs.bake-file }} \
            ${{ steps.meta-ubuntu-22-04.outputs.bake-file }} \
            ${{ steps.meta-ubuntu-20-04.outputs.bake-file }} \
            ${{ steps.meta-ubuntu-18-04.outputs.bake-file }} \
            > docker-bake.override.json
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Build and push
        uses: docker/bake-action@v2
        with:
          push: true
          files: |
            latex-ja/docker-bake.hcl
            docker-bake.override.json
          set: |
            *.cache-from=type=gha
            *.cache-to=type=gha,mode=max